# Generated by Django 5.2.7 on 2025-10-18 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanRequest',
            fields=[
                ('loan_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('interest_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('purpose', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('REPAID', 'Repaid')], default='PENDING', max_length=10)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('term_value', models.PositiveIntegerField(default=1, help_text='Loan term duration (numeric value)')),
                ('term_unit', models.CharField(choices=[('DAYS', 'Days'), ('WEEKS', 'Weeks'), ('MONTHS', 'Months')], default='DAYS', help_text='Loan term unit', max_length=10)),
                ('borrower_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_requests', to='account.borrowerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='LoanOffer',
            fields=[
                ('offer_id', models.AutoField(primary_key=True, serialize=False)),
                ('offered_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('offered_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('offer_status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined')], default='PENDING', max_length=10)),
                ('offer_date', models.DateTimeField(auto_now_add=True)),
                ('lender_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_offers', to='account.lenderprofile')),
                ('loan_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_offers', to='loan.loanrequest')),
            ],
        ),
    ]
