# Generated by Django 5.2.6 on 2025-12-10 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanRequest',
            fields=[
                ('loan_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('term', models.CharField(choices=[('1_MONTHS', '1 Month'), ('2_MONTHS', '2 Months'), ('3_MONTHS', '3 Months'), ('6_MONTHS', '6 Months'), ('12_MONTHS', '12 Months')], max_length=20)),
                ('purpose', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('FUNDED', 'Funded'), ('REPAID', 'Repaid'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_requests', to='account.user')),
            ],
        ),
        migrations.CreateModel(
            name='LoanOffer',
            fields=[
                ('offer_id', models.AutoField(primary_key=True, serialize=False)),
                ('offered_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('offered_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('message', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined')], default='PENDING', max_length=20)),
                ('offer_date', models.DateTimeField(auto_now_add=True)),
                ('lender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_offers', to='account.user')),
                ('loan_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='loan.loanrequest')),
            ],
        ),
    ]
