# Generated by Django 5.2.6 on 2025-12-13 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanRequest',
            fields=[
                ('loan_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('term', models.CharField(choices=[('7_DAYS', '7 Days'), ('15_DAYS', '15 Days'), ('1_MONTH', '1 Month'), ('2_MONTHS', '2 Months'), ('3_MONTHS', '3 Months'), ('4_MONTHS', '4 Months'), ('5_MONTHS', '5 Months'), ('6_MONTHS', '6 Months'), ('12_MONTHS', '12 Months')], max_length=20)),
                ('purpose', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('FUNDED', 'Funded'), ('REPAID', 'Repaid'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_requests', to='account.user')),
            ],
        ),
        migrations.CreateModel(
            name='LoanOffer',
            fields=[
                ('offer_id', models.AutoField(primary_key=True, serialize=False)),
                ('offered_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('offered_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('message', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined')], default='PENDING', max_length=20)),
                ('offer_date', models.DateTimeField(auto_now_add=True)),
                ('lender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_offers', to='account.user')),
                ('loan_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='loan.loanrequest')),
            ],
        ),
        migrations.CreateModel(
            name='ActiveLoan',
            fields=[
                ('active_loan_id', models.AutoField(primary_key=True, serialize=False)),
                ('principal_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('total_repayment', models.DecimalField(decimal_places=2, max_digits=12)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PAID', 'Paid'), ('DEFAULTED', 'Defaulted')], default='ACTIVE', max_length=20)),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liabilities', to='account.user')),
                ('lender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to='account.user')),
                ('loan_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='active_loan', to='loan.loanrequest')),
            ],
        ),
    ]
