# Generated by Django 5.2.6 on 2025-12-10 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('loan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveLoan',
            fields=[
                ('active_loan_id', models.AutoField(primary_key=True, serialize=False)),
                ('principal_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('total_repayment', models.DecimalField(decimal_places=2, max_digits=12)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PAID', 'Paid'), ('DEFAULTED', 'Defaulted')], default='ACTIVE', max_length=20)),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liabilities', to='account.user')),
                ('lender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to='account.user')),
                ('loan_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='active_loan', to='loan.loanrequest')),
            ],
        ),
    ]
