# Generated by Django 5.2.6 on 2025-09-27 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanoffer',
            name='offer_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='loanrequest',
            name='request_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
