# Generated by Django 5.2.6 on 2025-09-27 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0002_alter_loanoffer_offer_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanoffer',
            name='offered_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='loanoffer',
            name='offered_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='loanrequest',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='loanrequest',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='loanrequest',
            name='term_value',
            field=models.PositiveIntegerField(default=1, help_text='Loan term duration (numeric value)'),
        ),
    ]
