# Generated by Django 5.2.6 on 2025-12-12 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0002_activeloan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanrequest',
            name='term',
            field=models.CharField(choices=[('7_DAYS', '7 Days'), ('15_DAYS', '15 Days'), ('1_MONTH', '1 Month'), ('2_MONTHS', '2 Months'), ('3_MONTHS', '3 Months'), ('4_MONTHS', '4 Months'), ('5_MONTHS', '5 Months'), ('6_MONTHS', '6 Months'), ('12_MONTHS', '12 Months')], max_length=20),
        ),
    ]
