# Generated by Django 5.2.7 on 2025-10-18 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=40)),
                ('contact_number', models.CharField(max_length=20)),
                ('type', models.CharField(choices=[('L', 'Lender'), ('B', 'Borrower')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='BorrowerProfile',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='account.user')),
                ('income', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('credit_score', models.IntegerField(default=0)),
                ('employment_status', models.CharField(max_length=50)),
                ('profile_created_date', models.DateField(auto_now_add=True)),
            ],
            bases=('account.user',),
        ),
        migrations.CreateModel(
            name='LenderProfile',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='account.user')),
                ('investment_preference', models.CharField(max_length=200)),
                ('available_funds', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('min_investment_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('profile_created_date', models.DateField(auto_now_add=True)),
            ],
            bases=('account.user',),
        ),
    ]
