# Generated by Django 6.0 on 2025-12-15 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('loan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notification_id', models.AutoField(primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('LOAN_APPROVED', 'Loan Approved'), ('LOAN_OFFER', 'New Loan Offer'), ('REPAYMENT_DUE', 'Repayment Due'), ('VERIFICATION', 'Verification'), ('MESSAGE', 'New Message'), ('OFFER_ACCEPTED', 'Offer Accepted'), ('LOAN_FUNDED', 'Loan Funded'), ('LOAN_REJECTED', 'Loan Rejected'), ('REPAYMENT_MADE', 'Repayment Made'), ('WALLET', 'Wallet Transaction')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('priority', models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], default='MEDIUM', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('active_loan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='loan.activeloan')),
                ('loan_offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='loan.loanoffer')),
                ('loan_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='loan.loanrequest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='account.user')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read', 'created_at'], name='account_not_user_id_e1a5fb_idx')],
            },
        ),
    ]
