# Generated by Django 5.2.6 on 2025-09-27 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('L', 'Lender'), ('B', 'Borrower')], max_length=1),
        ),
    ]
