# Generated by Django 6.0 on 2025-12-15 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_message'),
        ('loan', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='notification',
            name='account_not_user_id_e1a5fb_idx',
        ),
        migrations.AddField(
            model_name='notification',
            name='action_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('LOAN_APPROVED', 'Loan Approved'), ('LOAN_OFFER', 'New Loan Offer'), ('REPAYMENT_DUE', 'Repayment Due'), ('VERIFICATION', 'Verification Status'), ('MESSAGE', 'New Message'), ('OFFER_ACCEPTED', 'Offer Accepted'), ('LOAN_REJECTED', 'Loan Rejected'), ('REPAYMENT_MADE', 'Repayment Made'), ('WALLET', 'Wallet Transaction'), ('SYSTEM', 'System Notification')], max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender', 'receiver', 'created_at'], name='account_mes_sender__b1dd51_idx'),
        ),
        migrations.RemoveField(
            model_name='notification',
            name='active_loan',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='loan_offer',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='loan_request',
        ),
    ]
