# Generated by Django 6.0 on 2025-12-16 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_message_edited_at_message_is_edited_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='message',
            name='account_mes_sender__b1dd51_idx',
        ),
        migrations.AddField(
            model_name='message',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='message',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name='message',
            name='loan_request',
        ),
        migrations.RemoveField(
            model_name='message',
            name='message_id',
        ),
        migrations.RemoveField(
            model_name='message',
            name='original_content',
        ),
    ]
