# Generated by Django 6.0 on 2025-12-16 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_remove_message_account_mes_sender__b1dd51_idx_and_more'),
        ('loan', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='message',
            name='edited_at',
        ),
        migrations.RemoveField(
            model_name='message',
            name='id',
        ),
        migrations.RemoveField(
            model_name='message',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='message',
            name='is_edited',
        ),
        migrations.AddField(
            model_name='message',
            name='loan_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='loan.loanrequest'),
        ),
        migrations.AddField(
            model_name='message',
            name='message_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender', 'receiver', 'created_at'], name='account_mes_sender__b1dd51_idx'),
        ),
    ]
