# Generated by Django 5.2.6 on 2025-12-13 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('loan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('transaction_data', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('D', 'Disbursement'), ('R', 'Repayment')], default='D', max_length=1)),
                ('status', models.CharField(choices=[('C', 'Completed'), ('P', 'Pending'), ('F', 'Failed')], default='P', max_length=1)),
                ('reference_number', models.CharField(blank=True, max_length=50, null=True)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('loan_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_transactions', to='loan.loanrequest')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_transactions', to='account.user')),
            ],
            options={
                'verbose_name_plural': 'Transactions',
                'ordering': ['-transaction_date'],
            },
        ),
    ]
