# Generated by Django 5.2.6 on 2025-09-27 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0002_alter_user_type'),
        ('loan', '0002_alter_loanoffer_offer_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('transaction_data', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('D', 'Disbursement'), ('R', 'Repayment')], default='D', max_length=1)),
                ('status', models.CharField(choices=[('C', 'Completed'), ('P', 'Pending'), ('F', 'Failed')], default='P', max_length=1)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('lender_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_transactions', to='account.lenderprofile')),
                ('loan_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='loan.loanrequest')),
            ],
            options={
                'verbose_name_plural': 'Transactions',
            },
        ),
    ]
